# led
set_property PACKAGE_PIN F6 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]
# CLK
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# DOOR
set_property PACKAGE_PIN P5 [get_ports door]
set_property IOSTANDARD LVCMOS33 [get_ports door]
# STATE
set_property PACKAGE_PIN P4 [get_ports state[2]]
set_property IOSTANDARD LVCMOS33 [get_ports state[2]]
set_property PACKAGE_PIN P3 [get_ports state[1]]
set_property IOSTANDARD LVCMOS33 [get_ports state[1]]
set_property PACKAGE_PIN P2 [get_ports state[0]]
set_property IOSTANDARD LVCMOS33 [get_ports state[0]]
# SELECT
set_property PACKAGE_PIN G1 [get_ports select[3]]
set_property IOSTANDARD LVCMOS33 [get_ports select[3]]
set_property PACKAGE_PIN F1 [get_ports select[2]]
set_property IOSTANDARD LVCMOS33 [get_ports select[2]]
set_property PACKAGE_PIN E1 [get_ports select[1]]
set_property IOSTANDARD LVCMOS33 [get_ports select[1]]
set_property PACKAGE_PIN G6 [get_ports select[0]]
set_property IOSTANDARD LVCMOS33 [get_ports select[0]]
# LIGHTS
set_property PACKAGE_PIN H2 [get_ports nixie[0]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[0]]
set_property PACKAGE_PIN D4 [get_ports nixie[1]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[1]]
set_property PACKAGE_PIN E3 [get_ports nixie[2]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[2]]
set_property PACKAGE_PIN D3 [get_ports nixie[3]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[3]]
set_property PACKAGE_PIN F4 [get_ports nixie[4]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[4]]
set_property PACKAGE_PIN F3 [get_ports nixie[5]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[5]]
set_property PACKAGE_PIN E2 [get_ports nixie[6]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[6]]
set_property PACKAGE_PIN D2 [get_ports nixie[7]]
set_property IOSTANDARD LVCMOS33 [get_ports nixie[7]]
# LLIGHT
set_property PACKAGE_PIN K1 [get_ports llight[2]]
set_property IOSTANDARD LVCMOS33 [get_ports llight[2]]
set_property PACKAGE_PIN H6 [get_ports llight[1]]
set_property IOSTANDARD LVCMOS33 [get_ports llight[1]]
set_property PACKAGE_PIN H5 [get_ports llight[0]]
set_property IOSTANDARD LVCMOS33 [get_ports llight[0]]
# RLIGHT
set_property PACKAGE_PIN L1 [get_ports rlight[2]]
set_property IOSTANDARD LVCMOS33 [get_ports rlight[2]]
set_property PACKAGE_PIN M1 [get_ports rlight[1]]
set_property IOSTANDARD LVCMOS33 [get_ports rlight[1]]
set_property PACKAGE_PIN K3 [get_ports rlight[0]]
set_property IOSTANDARD LVCMOS33 [get_ports rlight[0]]