# CLK
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# PLAYER 1
set_property PACKAGE_PIN P5 [get_ports door]
set_property IOSTANDARD LVCMOS33 [get_ports door]
# PLAYER 2
set_property PACKAGE_PIN R2 [get_ports miles[3]]
set_property IOSTANDARD LVCMOS33 [get_ports miles[3]]
set_property PACKAGE_PIN M4 [get_ports miles[2]]
set_property IOSTANDARD LVCMOS33 [get_ports miles[2]]
set_property PACKAGE_PIN N4 [get_ports miles[1]]
set_property IOSTANDARD LVCMOS33 [get_ports miles[1]]
set_property PACKAGE_PIN R1 [get_ports miles[0]]
set_property IOSTANDARD LVCMOS33 [get_ports miles[0]]

set_property PACKAGE_PIN P4 [get_ports state[2]]
set_property IOSTANDARD LVCMOS33 [get_ports state[2]]
set_property PACKAGE_PIN P3 [get_ports state[1]]
set_property IOSTANDARD LVCMOS33 [get_ports state[1]]
set_property PACKAGE_PIN P2 [get_ports state[0]]
set_property IOSTANDARD LVCMOS33 [get_ports state[0]]
# SELECT
set_property PACKAGE_PIN G1 [get_ports select[3]]
set_property IOSTANDARD LVCMOS33 [get_ports select[3]]
set_property PACKAGE_PIN F1 [get_ports select[2]]
set_property IOSTANDARD LVCMOS33 [get_ports select[2]]
set_property PACKAGE_PIN E1 [get_ports select[1]]
set_property IOSTANDARD LVCMOS33 [get_ports select[1]]
set_property PACKAGE_PIN G6 [get_ports select[0]]
set_property IOSTANDARD LVCMOS33 [get_ports select[0]]
# DISPLAY LIGHTS
set_property PACKAGE_PIN H2 [get_ports digit_num[0]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[0]]
set_property PACKAGE_PIN D4 [get_ports digit_num[1]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[1]]
set_property PACKAGE_PIN E3 [get_ports digit_num[2]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[2]]
set_property PACKAGE_PIN D3 [get_ports digit_num[3]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[3]]
set_property PACKAGE_PIN F4 [get_ports digit_num[4]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[4]]
set_property PACKAGE_PIN F3 [get_ports digit_num[5]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[5]]
set_property PACKAGE_PIN E2 [get_ports digit_num[6]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[6]]
set_property PACKAGE_PIN D2 [get_ports digit_num[7]]
set_property IOSTANDARD LVCMOS33 [get_ports digit_num[7]]
