webtalk_init -webtalk_dir C:/Users/luxyd/Desktop/counter/counter.sim/sim_1/behav/xsim/xsim.dir/sim_counter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  2 16:49:19 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ebf499de-611b-4c47-8ccf-56e08b15a239" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3e46b87ba60f4eab9b19bee340a515d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "37" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7876_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1065423431 -regid "" -xml C:/Users/luxyd/Desktop/counter/counter.sim/sim_1/behav/xsim/xsim.dir/sim_counter_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/luxyd/Desktop/counter/counter.sim/sim_1/behav/xsim/xsim.dir/sim_counter_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/luxyd/Desktop/counter/counter.sim/sim_1/behav/xsim/xsim.dir/sim_counter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
