# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luxyd/Desktop/car_lights/car_lights.srcs/sources_1/ip/counter_0/counter_0.xci
# IP: The module: 'counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luxyd/Desktop/car_lights/car_lights.gen/sources_1/ip/counter_0/constrs_1/new/con_counter.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/luxyd/Desktop/car_lights/car_lights.srcs/sources_1/ip/counter_0/counter_0.xci
# IP: The module: 'counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luxyd/Desktop/car_lights/car_lights.gen/sources_1/ip/counter_0/constrs_1/new/con_counter.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
